OBJS = src/hello.cpp
CC = g++

COMPILER_DEBUG_FLAGS = -w
COMPITER_RELEASE_FLAGS = -O3

LINKER_FLAGS = -lSDL2
OBJ_NAME = hello
RELEASE_DIR = realease
DEBUG_DIR = debug

BIN = build

all : RELEASE DEBUG

RELEASE: DELETE_RELEASE CREATE_RELEASE $(OBJS)
	$(CC) $(OBJS) $(COMPILER_DEBUG_FLAGS) $(COMPILER_RELEASE_FLAGS) $(LINKER_FLAGS) -o $(BIN)/$(RELEASE_DIR)/$(OBJ_NAME)

DEBUG: DELETE_DEBUG CREATE_DEBUG $(OBJS) 
	$(CC) $(OBJS) $(COMPILER_DEBUG_FLAGS) $(LINKER_FLAGS) -o $(BIN)/$(DEBUG_DIR)/$(OBJ_NAME)

clean: DELETE_DEBUG DELETE_RELEASE

DELETE_DEBUG:
	rm -rf $(BIN)/$(DEBUG_DIR)

DELETE_RELEASE: 
	rm -rf $(BIN)/$(RELEASE_DIR)

CREATE_DEBUG:
	mkdir -p $(BIN)/$(DEBUG_DIR)

CREATE_RELEASE:
	mkdir -p $(BIN)/$(RELEASE_DIR)
